variable "vpc_id_in" {}
variable "subnets_in" {}
variable "app_container_port_in" {}
variable "app_container_image_in" {}
variable "app_container_name_in" {}
variable "proxy_container_port_in" {}
variable "proxy_container_image_in" {}
variable "proxy_container_name_in" {}
variable "environment_name_in" {}
variable "https_listener_arn_in" {}
variable "backend_subdomain_name_in" {}