name: "Routing"
description: "Sets routing"
runs:
  using: "composite"
  steps:
    - name: Check changed directories...
      id: changed-files-dir-names
      uses: tj-actions/changed-files@v29.0.2
      with:
        dir_names: "true"

    - name: Show output
      run: echo ${{ steps.changed-files-dir-names.outputs.all_changed_and_modified_files }}
      shell: bash

    - name: List all changed directories...
      run: |
        for directory in ${{ steps.changed-files-dir-names.outputs.all_changed_and_modified_files }}; do
          echo "$directory changed"
        done
      shell: bash

    - name: Analysis
      id: analysis
      run: |
          if [[ ${{ contains(needs.changes.outputs.changed_directories, 'infra') }} ]]
          then
            echo "{infra_changed}={true}" >> $GITHUB_OUTPUT
          else
            echo "{infra_changed}={false}" >> $GITHUB_OUTPUT
          fi

          if [[ ${{ contains(needs.changes.outputs.changed_directories, 'back') }} ]]
          then
            echo "{back_changed}={true}" >> $GITHUB_OUTPUT
          else
            echo "{back_changed}={false}" >> $GITHUB_OUTPUT
          fi

          if [[ ${{ contains(needs.changes.outputs.changed_directories, 'front') }} ]]
          then
            echo "{front_changed}={true}" >> $GITHUB_OUTPUT
          else
            echo "{front_changed}={false}" >> $GITHUB_OUTPUT
          fi

    - name: Get short commit id
      id: sha
      run: echo "::set-output name=short::$(git rev-parse --short HEAD)"
      shell: bash

outputs:
  changed_directories: 
    value: ${{ steps.changed-files-dir-names.outputs.all_changed_and_modified_files }}
  short_sha: 
    value: ${{ steps.sha.outputs.short }}
  infra_changed: 
    value: ${{ steps.analysis.outputs.infra_changed }}
  back_changed: 
    value: ${{ steps.analysis.outputs.back_changed }}
  front_changed: 
    value: ${{ steps.analysis.outputs.front_changed }}