name: "Routing"
description: "Sets routing"
runs:
  using: "composite"
  steps:
    - name: Check changed directories...
      id: changed-files-dir-names
      uses: tj-actions/changed-files@v29.0.2
      with:
        dir_names: "true"

    - name: Show output
      run: echo ${{ steps.changed-files-dir-names.outputs.all_changed_and_modified_files }}
      shell: bash

    - name: List all changed directories...
      id: analysis
      run: |
        for directory in ${{ steps.changed-files-dir-names.outputs.all_changed_and_modified_files }}; do
          
          echo "$directory" | grep -E "^infra" 2>&1 > /dev/null
          if [[ $? -eq 0 ]]
          then
            echo "infra_changed=true" >> $GITHUB_OUTPUT
          else
            echo "infra_changed=false" >> $GITHUB_OUTPUT
          fi

          echo "$directory" | grep -E "^back" 2>&1 > /dev/null
          if [[ $? -q 0 ]]
          then
            echo "back_changed=true" >> $GITHUB_OUTPUT
          else
            echo "back_changed=false" >> $GITHUB_OUTPUT
          fi

          echo "$directory" | grep -E "^front" 2>&1 > /dev/null
          if [[ $? -q 0 ]]
          then
            echo "front_changed=true" >> $GITHUB_OUTPUT
          else
            echo "front_changed=false" >> $GITHUB_OUTPUT
          fi
        done
      shell: bash

    # - name: Analysis
    #   id: analysis
    #   shell: bash
    #   run: |
    #       if [[ ${{ contains(steps.changed-files-dir-names.outputs.all_changed_and_modified_files, 'infra') }} == true ]]
    #       then
    #         echo "infra_changed=true" >> $GITHUB_OUTPUT
    #       else
    #         echo "infra_changed=false" >> $GITHUB_OUTPUT
    #       fi

    #       if [[ ${{ contains(steps.changed-files-dir-names.outputs.all_changed_and_modified_files, 'back') }} == true ]]
    #       then
    #         echo "back_changed=true" >> $GITHUB_OUTPUT
    #       else
    #         echo "back_changed=false" >> $GITHUB_OUTPUT
    #       fi

    #       if [[ ${{ contains(steps.changed-files-dir-names.outputs.all_changed_and_modified_files, 'front') }} == true ]]
    #       then
    #         echo "front_changed=true" >> $GITHUB_OUTPUT
    #       else
    #         echo "front_changed=false" >> $GITHUB_OUTPUT
    #       fi

    - name: Get short commit id
      id: sha
      #run: echo "::set-output name=short::$(git rev-parse --short HEAD)"
      run: echo "short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      shell: bash

outputs:
  changed_directories: 
    value: ${{ steps.changed-files-dir-names.outputs.all_changed_and_modified_files }}
  short_sha: 
    value: ${{ steps.sha.outputs.short }}
  infra_changed: 
    value: ${{ steps.analysis.outputs.infra_changed }}
  back_changed: 
    value: ${{ steps.analysis.outputs.back_changed }}
  front_changed: 
    value: ${{ steps.analysis.outputs.front_changed }}