name: "Set tags"
description: "Set tags for Terraform variables"
inputs:
  short-sha:
    required: true
    description: "Shorter commit id"
  repository-name:
    required: true
    description: "Repository for the app"
    default: Demo
  filter-tag:
    required: true
    description: "Tag to filter images by"
    default: latest
  region:
    required: true
    description: "Repository region"
  branch:
    required: true
    description: "Images filter"
  tf-var-name:
    required: true
    description: "TF var name"
  changed:
    required: true
    description: "Check if image has been changed"
runs:
  using: "composite"
  steps:
    - name: Set image tag
      shell: bash
      run: |
        if [[ ${{ inputs.changed }} == true ]]
        then
          echo "TF_VAR_${{inputs.tf-var-name}}=${{ inputs.short-sha }}" | tee -a "$GITHUB_ENV"
        else 
          echo "Getting tags from latest image..."

          TAGS=$(aws ecr describe-images \
          --repository-name "${{ inputs.repository-name }}" \
          --image-ids imageTag="${{ inputs.filter-tag }}" \
          --region "${{ inputs.region }}")
          
          TAG=$(echo "$TAGS" \
          | jq '.imageDetails[].imageTags' \
          | jq \
          --arg BRANCH "${{ inputs.branch }}" \
          --arg FILTER "${{ inputs.filter-tag }}" \
          'del(.[] | select(. == $BRANCH or . == $FILTER))[]' \
          | tr -d '"' \
          | tail -n1)

          echo "TF_VAR_${{inputs.tf-var-name}}=${TAG}" | tee -a "$GITHUB_ENV"
        fi