on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Run changed-files with dir_names
        id: changed-files-dir-names
        uses: tj-actions/changed-files@v29.0.2
        with:
          dir_names: "true"

      - name: List all changed directories
        run: |
          for directory in ${{ steps.changed-files-dir-names.outputs.all_changed_and_modified_files }}; do
            echo "$directory was changed"
          done
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-2"

      - name: Update infrastructure
        if: contains(steps.changed-files-dir-names.outputs.all_changed_and_modified_files, 'infrastructure')
        run: |
          echo "Updating infrastructure !!!"
          IMAGE_EXISTS=$(aws ecr list-images --repository-name ecr-simplehttp --filter tagStatus=TAGGED --region us-east-2 | jq '.imageIds[].imageTag' | grep -v null | tr -d '"' | grep -c latest)

          if [[ ${IMAGE_EXISTS} -eq 1 ]]; then
            echo "Image exists!"
            echo "buildImage=false" >> $GITHUB_ENV
          else
            echo "Image does not exist!"
            echo "buildImage=true" >> $GITHUB_ENV
          fi

      - name: Building initial image...
        if: contains(steps.changed-files-dir-names.outputs.all_changed_and_modified_files, 'infrastructure') && env.buildImage == true
        uses: docker/build-push-action@v2
        with:
          context: "./backend/"
          file: "./backend/Dockerfile"
          push: false

      - name: Update frontend
        if: contains(steps.changed-files-dir-names.outputs.all_changed_and_modified_files, 'frontend')
        run: |
          echo "Updating frontend"
          
        
      - name: Update backend
        if: contains(steps.changed-files-dir-names.outputs.all_changed_and_modified_files, 'backend')
        run: echo "Updating backend"
      
      - name: Try build
        if: contains(steps.changed-files-dir-names.outputs.all_changed_and_modified_files, 'backend')
        uses: docker/build-push-action@v2
        with:
          context: "./backend/"
          file: "./backend/Dockerfile"
          push: false
