on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Run changed-files with dir_names
        id: changed-files-dir-names
        uses: tj-actions/changed-files@v29.0.2
        with:
          dir_names: "true"

      - name: List all changed directories
        run: |
          for directory in ${{ steps.changed-files-dir-names.outputs.all_changed_and_modified_files }}; do
            echo "$directory was changed"
          done

      - name: Update infrastructure
        if: contains(steps.changed-files-dir-names.outputs.all_changed_and_modified_files, 'infrastructure')
        run: |
          echo "Updating infrastructure"
          pwd

      - name: Update frontend
        if: contains(steps.changed-files-dir-names.outputs.all_changed_and_modified_files, 'frontend')
        run: |
          echo "Updating frontend"
          
        
      - name: Update backend
        if: contains(steps.changed-files-dir-names.outputs.all_changed_and_modified_files, 'backend')
        run: echo "Updating backend"
      
      - name: Try build
        if: contains(steps.changed-files-dir-names.outputs.all_changed_and_modified_files, 'backend')
        uses: docker/build-push-action@v2
        with:
          context: "./backend/"
          file: "./backend/Dockerfile"
          push: false
