on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

concurrency:
  group: ${{ github.ref_name }}


env:
  AWS_REGION: "us-east-2"
  FRONTEND_REPOSITORY_NAME: "frontend"
  BACKEND_REPOSITORY_NAME: "backend"
  BACKEND_PROXY_REPOSITORY_NAME: "proxy"
  ECR_REPOSITORY_URL: "454624638483.dkr.ecr.us-east-2.amazonaws.com"
  ENVIRONMENT: ${{ github.ref_name }}
  PROXY_PORT: 80
  APP_PORT: 8080
  APP_HOST: localhost
  FILTER_TAG: latest
  PROXY_DIRECTORY: 'proxy'
  NODEJS_DIRECTORY: 'nodejs'
  BACKEND_DIRECTORY: 'tier2'
  INFRASTRUCTURE_DIRECTORY: 'infra'

jobs:
  changes:
    name: "Routing"
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    steps:

      - name: Download repository...
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Routing
        id: routing
        uses: ./.github/actions/routing

    outputs:
      changed_directories: ${{ steps.routing.outputs.changed_directories }}
      short_sha: ${{ steps.routing.outputs.short_sha }}
      
  infrastructure:
    name: Infrastructure
    needs: changes
    runs-on: ubuntu-latest
    if: |
      always() &&
      needs.changes.result == 'success' &&
      contains(needs.changes.outputs.changed_directories, 'infra')
    steps:

      - name: Download repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Infrastructure
        id: infrastructure
        uses: ./.github/actions/infrastructure
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          short-sha: ${{ needs.changes.outputs.short_sha }}

  backend:
    name: Backend
    needs: [changes, infrastructure]
    runs-on: ubuntu-latest
    if: |
      always() &&
      needs.changes.result == 'success' &&
      (needs.infrastructure.result == 'success' || needs.infrastructure.result == 'skipped') &&
      contains(needs.changes.outputs.changed_directories, 'tier2')
    steps:

      - name: Download repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Backend
        id: backend
        uses: ./.github/actions/back
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          short-sha: ${{ needs.changes.outputs.short_sha }}
          changed-directories: ${{ needs.changes.outputs.changed_directories }}

  frontend:
    name: Frontend
    needs: [changes, infrastructure, backend]
    if: |
      always() &&
      needs.changes.result == 'success' &&
      (needs.infrastructure.result == 'success' || needs.infrastructure.result == 'skipped') &&
      (needs.backend.result == 'success' || needs.backend.result == 'skipped') &&
      contains(needs.changes.outputs.changed_directories, 'tier1')
    runs-on: ubuntu-latest
    env:
      FRONTEND_DIRECTORY: "tier1"
    steps:

      - name: Download repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Frontend
        id: frontend
        uses: ./.github/actions/front
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          short-sha: ${{ needs.changes.outputs.short_sha }}
          changed-directories: ${{ needs.changes.outputs.changed_directories }}