on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  AWS_REGION: "us-east-2"
  AWS_ECR_REPOSITORY: "test"
  AWS_ECR_REPO_URL: "454624638483.dkr.ecr.us-east-2.amazonaws.com/test"

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Run changed-files with dir_names
        id: changed-files-dir-names
        uses: tj-actions/changed-files@v29.0.2
        with:
          dir_names: "true"

      - name: List all changed directories
        run: |
          for directory in ${{ steps.changed-files-dir-names.outputs.all_changed_and_modified_files }}; do
            echo "$directory was changed"
          done
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-2"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set short sha
        id: sha
        run: echo "::set-output name=short::$(git rev-parse --short HEAD)"

      - name: Update infrastructure
        if: contains(steps.changed-files-dir-names.outputs.all_changed_and_modified_files, 'infrastructure')
        env:
          FILTER_TAG: "latest"

        run: |
          echo "Updating infrastructure !!!"
          #IMAGE_EXISTS=$(aws ecr list-images --repository-name ecr-simplehttp --filter tagStatus=TAGGED --region us-east-2 | jq '.imageIds[].imageTag' | grep -v null | tr -d '"' | grep -c latest)
          #IMAGE_EXISTS=$(aws ecr describe-images --repository-name ecr-simplehttp --image-ids imageTag=latest --region us-east-2 | jq '.imageDetails[].imageTags[]' | tr -d '"' | fgrep -v "latest" | head -n1)

          IMAGES_COUNT=$(aws ecr list-images --repository-name "${AWS_ECR_REPOSITORY}" --region "${AWS_REGION}" | jq '.imageIds | length')

          if [[ ${IMAGES_COUNT} -gt 0 ]]
          then

            images=$(aws ecr describe-images --repository-name "${AWS_ECR_REPOSITORY}" --image-ids imageTag="${FILTER_TAG}" --region "${AWS_REGION}")
            tag=$(echo "$images" | jq '.imageDetails[].imageTags' | jq 'del(.[] | select(. == "${{ github.ref_name }}" or . == "latest"))[]' | tr -d '"')

            if [[ $(echo $tag | wc -l) -gt 0 ]]
            then
              echo "Image already exists, going to Terraform!!!"
              echo "buildImage=false" >> "$GITHUB_ENV"
              echo "TF_VAR_image_tag=${tag}" >> "$GITHUB_ENV"
            else
              echo "Latest tag does not exits, something wrong, exiting..."
              exit 1
            fi
          else
              echo "There are no images, will build one!!!"
              echo "buildImage=true" >> "$GITHUB_ENV"
          fi

      - name: Building initial image...
        if: contains(steps.changed-files-dir-names.outputs.all_changed_and_modified_files, 'infrastructure') && env.buildImage == 'true'
        uses: docker/build-push-action@v2
        with:
          context: "./backend/"
          file: "./backend/Dockerfile"
          push: false

      - name: Update frontend
        if: contains(steps.changed-files-dir-names.outputs.all_changed_and_modified_files, 'frontend')
        run: |
          echo "Updating frontend"
          
        
      - name: Update backend
        if: contains(steps.changed-files-dir-names.outputs.all_changed_and_modified_files, 'backend')
        run: echo "Updating backend"
      
      - name: Try build
        if: contains(steps.changed-files-dir-names.outputs.all_changed_and_modified_files, 'backend')
        uses: docker/build-push-action@v2
        with:
          context: "./backend/"
          file: "./backend/Dockerfile"
          push: true
          tags: | 
            ${{ env.AWS_ECR_REPO_URL }}:latest
            ${{ env.AWS_ECR_REPO_URL }}:${{ github.ref_name }}
            ${{ env.AWS_ECR_REPO_URL }}:${{ steps.sha.outputs.short }}
